apiVersion: v1
kind: Pod
metadata:
  name: my-command-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-containe
    image: busybox
    command: ['echo']
    args: ['This is my custom arg']
  restartPolicy: Never
