apiVersion: v1
kind: Pod
metadata:
  name: my-ns-pod
  namespace: my-ns
  labels:
    app: myapp
spec:
  containers:
  - name: my-appcontainer
    image: busybox
    command: ['sh', '-c', 'while true; do echo Hello K8s!; sleep 1; done']

