apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pi2
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pi2
            image: ubuntu 
            args:
            - perl
            - -Mbignum=bpi
            - -wle
            - print bpi(2000) 
          restartPolicy: OnFailure
