apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-deployment2
spec:
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 1 
  replicas: 9
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.1
        ports:
        - containerPort: 80
